Add technology choices
com-pas/compas-architecture pull request #49
Opened 2020-12-07 08:49 UTC by Flurb

Added an overview!

2020-12-07 10:19 UTC, Sander3003 requested changes

2020-12-07 10:19 UTC, Sander3003 commented on images/Current_Technology_Choices_Overview.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="721px" height="701px" viewBox="-0.5 -0.5 721 701" content="&lt;mxfile host=&quot;app.diagrams.n
The use of Github / Github actions can be mentiond outside the image? It also fine to make a seperate image for the code development and testing (workflow).

2020-12-09 15:36 UTC, Flurb commented on images/Current_Technology_Choices_Overview.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="721px" height="701px" viewBox="-0.5 -0.5 721 701" content="&lt;mxfile host=&quot;app.diagrams.n
Removed the Github information! 👍

2020-12-11 12:50 UTC, Sander3003 approved these changes

2020-12-12 13:43 UTC, merged