Provenance metadata research
com-pas/compas-architecture pull request #79
Opened 2021-04-19 14:34 UTC by Flurb

2021-04-20 07:22 UTC, Sander3003 requested changes
Please add the idea to store the prov data.

2021-04-20 07:22 UTC, Sander3003 commented on DATABASE_MANAGEMENT.md
> +## Provenance Overview
Where do you want to store de prov information in the database? In a seperate database?

2021-05-03 09:37 UTC, Sander3003 approved these changes
Looks good to me.

2021-05-03 09:44 UTC, merged

2021-05-04 10:13 UTC, Flurb commented on DATABASE_MANAGEMENT.md
> +In this case, we can extend the History item with so-called 'private' data, which will be the W3C PROV-XML data.
I'll add!